### ISSUE TITLE
adding Quantin 2007 / Hartmann 2007 Chronology functions?

### ISSUE THREAD

**Issue by AndrewAnnex** [ggmichael/craterstats#13]
While doing a lit review I cam across Quantin et al 2007 [10.1016/j.icarus.2006.07.008](https://doi.org/10.1016/j.icarus.2006.07.008) and Hartmann et al 2007 [10.1016/j.icarus.2006.09.009](https://doi.org/10.1016/j.icarus.2006.09.009)
for a chronology function with a decreasing production rate past 3 Gyr. I haven't looked at the full citation graph to work it out, but as far as I can tell Hartmann 2007 is not cited by the @ggmichael 2013 paper. Perhaps there is some more recent thinking on this that makes the 2010 iteration more correct?

In the paper as far as I can tell the full neukum style numerical expression coefficients are not provided in either paper. An expression is given in Hartmann 2007 but I think it just determines the linear trend post 3 Gya rather than the typical expression

**Comment by ggmichael** [comment]
For the 2013 paper, I was in contact with W. Hartmann to make sure the results the software was producing were correct. It sounds like I would need to do the same for Quantin et al 2007. Hartmann 2007 was a lunar, not Mars, paper. 

There is the possibility for the user to add new chronology systems or, if needed, I'm glad to collaborate on such topics in the context of an actual application.
