### ISSUE TITLE
Inconsistencies in Setup

### ISSUE THREAD

**Issue by ColteRodriguez** [ggmichael/craterstats#22]
1. $ cd demo works in terminal but /demo doesn't appear to be a subdirectory within craterstats parent directory, only openable with $ open .    -- This is fine, but annoying to realize and would have benefitted from some mention in the Readme
2. The ',' syntax for defining an overplot does not work on Mac OS. Still working this one out

**Comment by ColteRodriguez** [comment]
Update: ',' overplot syntax does work, but '&' can be misinterpreted as a function call. Easily fixed by passing params as string. E.g:

~ % craterstats -pr hartmann -cs 'h&d2016' --equilibrium hartmann -title Hartmann style plot -subtitle 'with H&D 2016 production function' -isochrons 4s,3.7s,3s,1,.1,.01,.001,1e-4,1e-5,1e-6,1e-7,1e-8,1e-9 -p source=%sample%/Pickering.scc,psym=o

**Comment by ggmichael** [comment]
/demo is created in the directory where you run 'craterstats -demo'. Made explicit in readme.
