### ISSUE TITLE
link to Freie Uni. tutorials

### ISSUE THREAD

**Issue by thareUSGS** [ggmichael/craterstats#23]
The original https site that maintained the tutorials from the 2012 workshop has essentially been deprecated but some of the files are "safed" in a S3 cloud bucket. Thus, we might want to grab them and post them here as is (or as PDFs). For now, they are available [here](https://asc-pds-services.s3.us-west-2.amazonaws.com/pigpen/index.html#tutorials_FreieUni_Workshop2012):

**Comment by ggmichael** [comment]
thanks - added to github.
