### ISSUE TITLE
Question: perhaps fork craterstats GUI since student program is wrapped?

### ISSUE THREAD

**Issue by thareUSGS** [ggmichael/craterstats#24]
While never the intent of the student project, if you deem it worthy, I would be excited for you to take over the craterstats GUI. As they are graduating, I don't see their team supporting it further.
https://github.com/LWATLINGTON02/CraterStats-Capstone

Perhaps a fork here or simply linking to their github from this site.

I have also forked their project and can try to offer updates also. I would still love to see both eventually on PlanetaryPy, but I know there are still some roadblocks.

**Comment by ggmichael** [comment]
They made a very good start with this project in so short a time. Certainly it's worth developing further - I'll have to see whether I can find time for it.
