### ISSUE TITLE
How to read impact crater data that includes diameter, longitude, and latitude positions

### ISSUE THREAD

**Issue by xiangchimango** [ggmichael/craterstats#25]
I tried reading my data, but I was informed that there was an issue with the attributes, and it still couldn't be read after converting it to an SCC file. I was wondering if there are any steps in between that I might have missed. I look forward to your response.

**Comment by ggmichael** [comment]
I suggest you to use a .diam file as in the given samples and below, setting the crater table format to:

crater = {diameter, lon, lat


# Empty sample .diam file for Craterstats
#
# new format introduced 2014.03.04
# previous formats should still work, but this one to be preferred
#
#
# area, km^2
area = 100.
#
#
# table below may include any of the following field combinations:
#
#              km        -      deg  deg
# crater = {diameter
# crater = {diameter, fraction
# crater = {diameter, fraction, lon, lat
#
# 
crater = {diameter
1.1
2.3
3.0
1.7
}
