### ISSUE TITLE
Craterstats does not read .diam files

### ISSUE THREAD

**Issue by dgorin1** [ggmichael/craterstats#4]
![issue](https://user-images.githubusercontent.com/91497821/134971736-ebe703ea-80fe-4f5b-a192-b1d16da9904d.JPG)
When I attempt to have craterstats read either of the .diam example files provided in the package, I receive a long string of errors. I first noticed this when trying to read in my own modified .diam file. I then tried to read in the demo files to ensure I was doing so correctly and discovered this problem. Is this a known issue?

Thanks.

**Comment by ggmichael** [comment]
Thanks for the report - it's fixed now
