### ISSUE TITLE
suggested improvements

### ISSUE THREAD

**Issue by AndrewAnnex** [ggmichael/craterstats#8]
I've been using the craterstats cli and learning more about the different options using the demo scripts and my own data, I have been keeping a mental list, presented below, of general improvements/additions that I won't have time to contribute myself but others may find the time to get around to. 

1) add ability to add provide custom legend labels (name parameter doesn't seem to let me specify which fit mode was used)
2) add ability to change width/height of poisson curves, display mode to only show the  poisson curves with the age information 
3) add some examples for setting the x range explicitly, either one of the other options disabled it or it doesn't work for all modes but I don't need bins below a kilometer or so to be displayed or over 100 km, so being able to set the range would be nice

**Comment by AndrewAnnex** [comment]
1.) I would rather not modify filenames to change the legend labels, I may have metadata in the file names that I want to keep out of the plots for example (dates or versions for example), so being a bit more flexible there would be nice. I think the mixed mode is kinda useful to compare the poisson derived ages to more conventional curve fitting ages (when N is high enough they converge more or less.

2. the science case is simply that the poisson plots are too small to read especially for slides, not sure what you mean by "combined Poisson curve". I would prefer being able to increase the size of the subplot or add the ability to only plot/export the subplots curves so that I can just make the figure how I want it to look. If by "combined" you mean multiple curves in a single subplot that's not really what I am looking for, but could be potentially useful if you were dating multiple surfaces from a single datafile, but I think it would be better to allow multiple data files to be used instead (e.g. counts for specific/non overlapping areas to conserve space in presentations/papers). 

3. I agree by default it should replicate his style exactly, but I should be able to override the behavior if all my craters are squished into a smaller diameter range. What exactly is the harm of allowing slight modifications to the x axis range?

**Comment by ggmichael** [comment]
1. ok - agreed for the flexible labels. 
2. I was thinking you meant the latter - you might want to show multiple measurments of surfaces affected by a common process. The previous craterstats had some font/symbol sizing to cater for slide/poster readability - the framework is there for this in this version, but it needs a cli option and some testing.
3. It's possible, of course. Nobody's done it before. You could create a custom/modified PF definition if you really want it.

**Comment by AndrewAnnex** [comment]
oh so for 3 I am not thinking of modifying the crater production function definition, I mean just limiting the plot area (using matplotlib xlim/ylim functions) to modify which bins are in view.  All the math would stay exactly the same, I just don't need to waste plot area for diameters smaller than say 1km and larger than 100 km for example, so the xaxis would just span 1-100 km rather than 0.01-1000km or whatever.

**Comment by ggmichael** [comment]
1. You can now override the default dataset name (the filename) with -name <yourname> in the subplot definition.
2. Lettering and Poisson subplot size can be altered with, e.g.  -pt_size 12. 
3. I understand what you're saying - I allow it for all styles except Hartmann's. I won't make this change because he intended it that way.
